/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bloodtestscheduler;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author shemeneroje
 */
public class BTSGUI extends javax.swing.JFrame {
    private ArrayList<Patient> patientList;
    private PatientQueue patientQueue;


    /**
     * Creates new form BTSGUI
     */
    public BTSGUI() {
        initComponents();
        patientList = new ArrayList<>(); // Initialize the patient list
        patientQueue = new PatientQueue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        priorityRg = new javax.swing.ButtonGroup();
        HospitalBg = new javax.swing.ButtonGroup();
        fAppRg = new javax.swing.ButtonGroup();
        missAppRg = new javax.swing.ButtonGroup();
        TitleLbn = new javax.swing.JLabel();
        nameLbn = new javax.swing.JLabel();
        ageLbn = new javax.swing.JLabel();
        gpdLbn = new javax.swing.JLabel();
        priorityLbn = new javax.swing.JLabel();
        hospitalLbn = new javax.swing.JLabel();
        queueLbn = new javax.swing.JLabel();
        missedALbn = new javax.swing.JLabel();
        displayBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        missedATa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        queueTa = new javax.swing.JTextArea();
        nameTf = new javax.swing.JTextField();
        lowRb = new javax.swing.JRadioButton();
        mediumRb = new javax.swing.JRadioButton();
        highRb = new javax.swing.JRadioButton();
        yesRb = new javax.swing.JRadioButton();
        noRb = new javax.swing.JRadioButton();
        ageTf = new javax.swing.JTextField();
        gpdTf = new javax.swing.JTextField();
        missALbn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        appointmentLbn = new javax.swing.JLabel();
        appYesRb = new javax.swing.JRadioButton();
        appNoRb = new javax.swing.JRadioButton();
        missYesRb = new javax.swing.JRadioButton();
        missNoRb = new javax.swing.JRadioButton();
        sortBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLbn.setBackground(new java.awt.Color(0, 102, 204));
        TitleLbn.setFont(new java.awt.Font("Helvetica Neue", 3, 48)); // NOI18N
        TitleLbn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLbn.setText("Blood Test Scheduler");
        TitleLbn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        nameLbn.setText("Name");

        ageLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ageLbn.setText("Age");

        gpdLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        gpdLbn.setText("GP Details");

        priorityLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        priorityLbn.setText("Priority");

        hospitalLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hospitalLbn.setText("Are You Coming from a Hospital?");

        queueLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        queueLbn.setText("Queue");

        missedALbn.setBackground(new java.awt.Color(255, 51, 51));
        missedALbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        missedALbn.setText("Missed Appointments");

        displayBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        missedATa.setColumns(20);
        missedATa.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        missedATa.setRows(5);
        jScrollPane1.setViewportView(missedATa);

        queueTa.setColumns(20);
        queueTa.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        queueTa.setRows(5);
        jScrollPane2.setViewportView(queueTa);

        nameTf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        priorityRg.add(lowRb);
        lowRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lowRb.setText("Low");

        priorityRg.add(mediumRb);
        mediumRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        mediumRb.setText("Medium");

        priorityRg.add(highRb);
        highRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        highRb.setText("Urgent");
        highRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highRbActionPerformed(evt);
            }
        });

        HospitalBg.add(yesRb);
        yesRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        yesRb.setText("Yes");

        HospitalBg.add(noRb);
        noRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        noRb.setText("No");

        ageTf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        gpdTf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        missALbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        missALbn.setText("Did You Miss Your Last Appointment?");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        appointmentLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        appointmentLbn.setText("Is This Your First Appointment ?");

        fAppRg.add(appYesRb);
        appYesRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        appYesRb.setText("Yes ");

        fAppRg.add(appNoRb);
        appNoRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        appNoRb.setText("No");

        missAppRg.add(missYesRb);
        missYesRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        missYesRb.setText("Yes");

        missAppRg.add(missNoRb);
        missNoRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        missNoRb.setText("No");

        sortBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sortBtn.setText("Sort");
        sortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(missALbn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(queueLbn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sortBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(missedALbn)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(missYesRb)
                                .addGap(28, 28, 28)
                                .addComponent(missNoRb)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))))
                .addGap(9, 9, 9)
                .addComponent(saveBtn)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TitleLbn)
                        .addGap(161, 161, 161))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(appointmentLbn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(appYesRb)
                                .addGap(18, 18, 18)
                                .addComponent(appNoRb)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yesRb)
                        .addGap(50, 50, 50)
                        .addComponent(noRb)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(gpdLbn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gpdTf))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(nameLbn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(ageLbn)
                                        .addGap(72, 72, 72)
                                        .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalLbn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(priorityLbn)
                                        .addGap(18, 18, 18)
                                        .addComponent(lowRb)
                                        .addGap(18, 18, 18)
                                        .addComponent(mediumRb)
                                        .addGap(18, 18, 18)
                                        .addComponent(highRb))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(displayBtn)))
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLbn)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbn)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLbn)
                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityLbn)
                    .addComponent(lowRb)
                    .addComponent(mediumRb)
                    .addComponent(highRb))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(hospitalLbn)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yesRb)
                                    .addComponent(noRb)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gpdLbn)
                                    .addComponent(gpdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(appointmentLbn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(appYesRb)
                                    .addComponent(appNoRb))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(missALbn)
                                    .addComponent(saveBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(missYesRb)
                            .addComponent(missNoRb))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missedALbn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queueLbn)
                    .addComponent(sortBtn))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void highRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highRbActionPerformed

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        // Displaying the patient list in the queue area
        StringBuilder sb = new StringBuilder();
        for (Patient patient : patientList) {
            sb.append(patient.toString()).append("\n");
        }
        queueTa.setText(sb.toString());

        // Display missed appointments in the missed appointments area
        StringBuilder missedSb = new StringBuilder();
        for (Patient patient : patientList) {
            if (patient.isMissedAppointment()) {
                missedSb.append(patient.toString()).append("\n");
            }
        }
        missedATa.setText(missedSb.toString());

    }//GEN-LAST:event_displayBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
            String name = nameTf.getText();
    String ageText = ageTf.getText();
    String gpd = gpdTf.getText();
    String priority = getPriority();
    boolean fromHospital = yesRb.isSelected();
    boolean missedAppointment = missYesRb.isSelected();

    // Validate name
    if (name.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a valid name.");
        return;
    }

    // Validate age (ensure it's a number and within a reasonable range)
    int age = -1;
    try {
        age = Integer.parseInt(ageText);
        if (age <= 0 || age > 120) {  // Checking for valid age range
            throw new NumberFormatException();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid age between 1 and 120.");
        return;  // Exit the method to avoid creating an invalid patient
    }

    // Validate priority (ensure a valid priority is selected)
    if (priority == null || priority.equals("None")) {
        JOptionPane.showMessageDialog(this, "Please select a valid priority.");
        return;
    }

    // Creating a new Patient object
    Patient newPatient = new Patient(name, age, gpd, priority, fromHospital, missedAppointment);

    // Adding patient to the list
    patientList.add(newPatient);
    
    // Adding patient to the patientQueue
    patientQueue.enqueue(newPatient);


    // Save the data to the file
    saveToFile();

    // Showing a message
    JOptionPane.showMessageDialog(this, "Patient added successfully!");
    
    // Clear input fields https://coderanch.com/t/615040/java/clear-Multiple-text-fields
    nameTf.setText("");
    ageTf.setText("");
    gpdTf.setText("");
    priorityRg.clearSelection();
    HospitalBg.clearSelection();
    fAppRg.clearSelection();
    missAppRg.clearSelection();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void sortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortBtnActionPerformed
        // TODO add your handling code here:
        // Call the getPatientDetails method to sort the queue and get the sorted details as a string
        String sortedDetails = patientQueue.getPatientDetails();

        // Ensure the queue is actually sorted and print debug info if necessary
        System.out.println("Sorted patient details:\n" + sortedDetails);

        // Display the sorted details in the JTextArea (queueTa)
        queueTa.setText(sortedDetails);
    }//GEN-LAST:event_sortBtnActionPerformed
    
    private String getPriority() {
        if (lowRb.isSelected()) return "Low";
        if (mediumRb.isSelected()) return "Medium";
        if (highRb.isSelected()) return "Urgent";
        return "None";
    }

    private void saveToFile() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("patients.txt", true))) {
            for (Patient patient : patientList) {
                writer.write(patient.toString());  // Customize Patient toString method as needed
                writer.newLine();
            }
            JOptionPane.showMessageDialog(this, "Patient data saved!");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving patient data.");
            
        }
        
        
        
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BTSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup HospitalBg;
    private javax.swing.JLabel TitleLbn;
    private javax.swing.JLabel ageLbn;
    private javax.swing.JTextField ageTf;
    private javax.swing.JRadioButton appNoRb;
    private javax.swing.JRadioButton appYesRb;
    private javax.swing.JLabel appointmentLbn;
    private javax.swing.JButton displayBtn;
    private javax.swing.ButtonGroup fAppRg;
    private javax.swing.JLabel gpdLbn;
    private javax.swing.JTextField gpdTf;
    private javax.swing.JRadioButton highRb;
    private javax.swing.JLabel hospitalLbn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton lowRb;
    private javax.swing.JRadioButton mediumRb;
    private javax.swing.JLabel missALbn;
    private javax.swing.ButtonGroup missAppRg;
    private javax.swing.JRadioButton missNoRb;
    private javax.swing.JRadioButton missYesRb;
    private javax.swing.JLabel missedALbn;
    private javax.swing.JTextArea missedATa;
    private javax.swing.JLabel nameLbn;
    private javax.swing.JTextField nameTf;
    private javax.swing.JRadioButton noRb;
    private javax.swing.JLabel priorityLbn;
    private javax.swing.ButtonGroup priorityRg;
    private javax.swing.JLabel queueLbn;
    private javax.swing.JTextArea queueTa;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton sortBtn;
    private javax.swing.JRadioButton yesRb;
    // End of variables declaration//GEN-END:variables
}
