/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bloodtestscheduler;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author shemeneroje
 */
public class BTSGUI extends javax.swing.JFrame {
    private ArrayList<Patient> patientList;


    /**
     * Creates new form BTSGUI
     */
    public BTSGUI() {
        initComponents();
        patientList = new ArrayList<>(); // Initialize the patient list
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        TitleLbn = new javax.swing.JLabel();
        nameLbn = new javax.swing.JLabel();
        ageLbn = new javax.swing.JLabel();
        gpdLbn = new javax.swing.JLabel();
        priorityLbn = new javax.swing.JLabel();
        hospitalLbn = new javax.swing.JLabel();
        queueLbn = new javax.swing.JLabel();
        missedALbn = new javax.swing.JLabel();
        displayBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        missedATa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        queueTa = new javax.swing.JTextArea();
        nameTf = new javax.swing.JTextField();
        lowRb = new javax.swing.JRadioButton();
        mediumRb = new javax.swing.JRadioButton();
        highRb = new javax.swing.JRadioButton();
        yesRb = new javax.swing.JRadioButton();
        noRb = new javax.swing.JRadioButton();
        ageTf = new javax.swing.JTextField();
        gpdTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLbn.setBackground(new java.awt.Color(0, 102, 204));
        TitleLbn.setFont(new java.awt.Font("Helvetica Neue", 3, 48)); // NOI18N
        TitleLbn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLbn.setText("Blood Test Scheduler");

        nameLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        nameLbn.setText("Name");

        ageLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ageLbn.setText("Age");

        gpdLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        gpdLbn.setText("GP Details");

        priorityLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        priorityLbn.setText("Priority");

        hospitalLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        hospitalLbn.setText("Are You Coming from a Hospital?");

        queueLbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        queueLbn.setText("Queue");

        missedALbn.setBackground(new java.awt.Color(255, 51, 51));
        missedALbn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        missedALbn.setText("Missed Appointments");

        displayBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        missedATa.setColumns(20);
        missedATa.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        missedATa.setRows(5);
        jScrollPane1.setViewportView(missedATa);

        queueTa.setColumns(20);
        queueTa.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        queueTa.setRows(5);
        jScrollPane2.setViewportView(queueTa);

        nameTf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        buttonGroup1.add(lowRb);
        lowRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lowRb.setText("Low");

        buttonGroup1.add(mediumRb);
        mediumRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        mediumRb.setText("Medium");

        buttonGroup1.add(highRb);
        highRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        highRb.setText("High");
        highRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highRbActionPerformed(evt);
            }
        });

        buttonGroup2.add(yesRb);
        yesRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        yesRb.setText("Yes");

        buttonGroup2.add(noRb);
        noRb.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        noRb.setText("No");

        ageTf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        gpdTf.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameLbn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(337, 337, 337)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hospitalLbn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(priorityLbn)
                                        .addGap(18, 18, 18)
                                        .addComponent(lowRb)
                                        .addGap(18, 18, 18)
                                        .addComponent(mediumRb)
                                        .addGap(18, 18, 18)
                                        .addComponent(highRb))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(TitleLbn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gpdLbn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLbn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gpdTf, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addComponent(yesRb)
                                .addGap(18, 18, 18)
                                .addComponent(noRb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(queueLbn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(missedALbn)
                                .addGap(93, 93, 93))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(displayBtn)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLbn)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbn)
                    .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityLbn)
                    .addComponent(lowRb)
                    .addComponent(mediumRb)
                    .addComponent(highRb))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLbn)
                    .addComponent(ageTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpdLbn)
                            .addComponent(gpdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(hospitalLbn)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yesRb)
                            .addComponent(noRb))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(saveBtn)
                                .addGap(18, 18, 18)
                                .addComponent(displayBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(missedALbn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(queueLbn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void highRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highRbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highRbActionPerformed

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        // Display the patient information in the queue and missed appointments
        StringBuilder queueText = new StringBuilder();
        StringBuilder missedText = new StringBuilder();

        for (Patient patient : patientList) {
            // Append patient details to the queue display
            queueText.append(patient.toString()).append("\n");
            
            //missedText.append(patient.getName()).append("\n");
        }

        queueTa.setText(queueText.toString());  // Show queue info
        missedATa.setText(missedText.toString());  // Show missed appointments                                         
        
    }//GEN-LAST:event_displayBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        // Save the patient data
        String name = nameTf.getText();
        String age = ageTf.getText();
        String gpd = gpdTf.getText();

        String priority = "Low";
        if (mediumRb.isSelected()) {
            priority = "Medium";
        } else if (highRb.isSelected()) {
            priority = "High";
        }

        boolean isHospitalPatient = yesRb.isSelected();
        
        // Validate inputs before creating a new patient
        if (name.isEmpty() || age.isEmpty() || gpd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        try {
            int patientAge = Integer.parseInt(age); // Parse age to integer
            Patient newPatient = new Patient(name, patientAge, gpd, priority, isHospitalPatient);
            patientList.add(newPatient); // Add the new patient to the list

            // Clear the form fields
            nameTf.setText("");
            ageTf.setText("");
            gpdTf.setText("");
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid age. Please enter a valid number.");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BTSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BTSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLbn;
    private javax.swing.JLabel ageLbn;
    private javax.swing.JTextField ageTf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel gpdLbn;
    private javax.swing.JTextField gpdTf;
    private javax.swing.JRadioButton highRb;
    private javax.swing.JLabel hospitalLbn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton lowRb;
    private javax.swing.JRadioButton mediumRb;
    private javax.swing.JLabel missedALbn;
    private javax.swing.JTextArea missedATa;
    private javax.swing.JLabel nameLbn;
    private javax.swing.JTextField nameTf;
    private javax.swing.JRadioButton noRb;
    private javax.swing.JLabel priorityLbn;
    private javax.swing.JLabel queueLbn;
    private javax.swing.JTextArea queueTa;
    private javax.swing.JButton saveBtn;
    private javax.swing.JRadioButton yesRb;
    // End of variables declaration//GEN-END:variables
}
